### ISSUE TITLE
快速示例不能正常启动运行

### ISSUE THREAD

**Issue by gzg1500521074** [apache/submarine#1066]
当我执行 "kubectl apply -f submarine-cloud-v2/artifacts/examples/example-submarine.yaml" 时，报了如下错误，请看截图。

<img width="1435" alt="image" src="https://github.com/apache/submarine/assets/24455273/5ba5548f-7b39-4480-b4a8-4a48bdb8cddb">

**Comment by cdmikechen** [comment]
Hi~ @gzg1500521074 
Can you try master branch in https://submarine.apache.org/docs/next/gettingStarted/quickstart.
0.7.0 currently has several known issues, we have fixed in the master branch.

**Comment by gzg1500521074** [comment]
谢谢，成功了。
