### ISSUE TITLE
helm install submarine ./helm-charts/submarine error

### ISSUE THREAD

**Issue by TaiJuWu** [apache/submarine#1075]
I followed quickstart (https://submarine.apache.org/docs/gettingStarted/quickstart)
At step 2: helm install submarine ./helm-charts/submarine

The error shows:
Error: INSTALLATION FAILED: An error occurred while checking for chart dependencies. You may need to run `helm dependency 
build` to fetch missing dependencies: found in Chart.yaml, but missing in charts/ directory: seldon-core-operato

After run `helm dependency build` also show:
Contents of linked file included and used
Error: Chart.yaml file is missing

**Comment by cdmikechen** [comment]
Hi~ 
If you want to use the codes for the master branch, you can refer to the link below:
https://submarine.apache.org/docs/next/gettingStarted/quickstart/
Since we will be releasing 0.8.0 soon, we recommend using the master branch documentation for deployment.
