### ISSUE TITLE
horovod support

### ISSUE THREAD

**Issue by jasstionzyf** [apache/submarine#159]
horovod: https://github.com/horovod/horovod

**Comment by jasstionzyf** [comment]
https://github.com/horovod/horovod/issues/1497 
it seems  that horovod can run hadoop yarn directly

**Comment by liuxunorg** [comment]
hi @jasstionzyf :-)
Thank you for your interest in the submarine project. We have plans to support horovod. The specific plan is still under discussion.
You can contact us via email(liuxun#apache.org) or WeChat(liuxun_org).

**Comment by jasstionzyf** [comment]
@liuxunorg   great!   
[ Https://github.com/horovod/horovod/pull/1525](Https://github.com/horovod/horovod/pull/1525) 
 Above issues have been resolved to support run horovod though spark on yarn.
 Maybe helpfull.

**Comment by jojochuang** [comment]
Thanks for the contribution! Please file an issue at the Apache JIRA system.

**Comment by jiwq** [comment]
Close this issue. If you should to tracking the feature, you can do it in https://issues.apache.org/jira/projects/SUBMARINE/issues
