### ISSUE TITLE
occurred an error when I execute "build_python_virtual_env.sh"

### ISSUE THREAD

**Issue by ChanaLii** [apache/submarine#196]
Can u tell me how to fix the error?
`Invalid requirement: '/opt/pysubmarine/.' It looks like a path. File '/opt/pysubmarine/.' does not exist.`

**Comment by pingsutw** [comment]
Hi @ChanaLii, This script is for mini-submarine to build a python virtual env.
The folder `/opt/pysubmarine/` is in mini-submarine for building `pysubmarine`

If you want to build `pysubmarine` by youself, just change `pip3 install /opt/pysubmarine/.`
to `pip3 install <path_to_submarine>/submarine-sdk/pysubmarine/ . `
