### ISSUE TITLE
Support to run submarine over Apache Ignite

### ISSUE THREAD

**Issue by john77eipe** [apache/submarine#278]
Any plans to support Apache Ignite as a data platform along with HDFS/Yarn and Kubernetes.

**Comment by liuxunorg** [comment]
hi, @john77eipe  , thank you for interest in the submarine project.
The current submarine project focuses on the process of machine learning.
For the time being, the community has not considered the data processing part too much.

You are welcome to continue to pay attention to the submarine project. :-)

**Comment by john77eipe** [comment]
Thank you for the response. Just now went through the docs. Looks like the focus is on compute resources alone.

**Comment by john77eipe** [comment]
Is there a discord or slack group where developers and users can connect?

**Comment by jiwq** [comment]
@john77eipe We encourage folks to use the email group first (http://submarine.apache.org/community/contributors.html#mailing-list) and the slack channel is https://join.slack.com/share/zt-h03yqy6s-BExKGw8amb6Nk4HpP1ARtw
