### ISSUE TITLE
Submarine Spark Security Plugin 对脱敏字段使用函数时，脱敏规则不起作用

### ISSUE THREAD

**Issue by liu372943162** [apache/submarine#313]
@yaooqinn 
当我进行脱敏字段直接查询时，可以正常起作用，但是当我们对脱敏字段使用函数时，例如 substring(id_no,0,18) ,此时脱敏将不起作用，将展示原文。

**Comment by liu372943162** [comment]
@yaooqinn 希望得到您的帮助

**Comment by pingsutw** [comment]
Also cc @liuxunorg

**Comment by yaooqinn** [comment]
Nice catch!

**Comment by liuxunorg** [comment]
@yaooqinn Are there any plans to solve this problem？

**Comment by yaooqinn** [comment]
Wii investigate this in next one or two weeks.

**Comment by yaooqinn** [comment]
Hi, @liu372943162 can you file a JIRA to help the community track this?

**Comment by liuxunorg** [comment]
@liu372943162 
Can you create a ticket here on the [SUBMARINE JIRA](https://issues.apache.org/jira/projects/SUBMARINE/issues/)?

**Comment by liu372943162** [comment]
https://issues.apache.org/jira/browse/SUBMARINE-531

thanks

**Comment by liu372943162** [comment]
@yaooqinn @liuxunorg 

First of all, thank you for your help，but There is also a small problem:

When I do single table query, it works well, but when I do association query, such as “select a.name, a.idno from test.table_user a join table_user B on a.idno = b.idno”, the throw an error：“Error:org.apache.spark.sql.AnalysisException :Reference `name` is ambiguous,could be: a.name,b.name.;line 1 pos 0 (state=,code=0)”
