### ISSUE TITLE
Username and Password

### ISSUE THREAD

**Issue by vinhdiesal** [apache/submarine#373]
I perform a `./submarine.sh` and pointed my browser to the URL, however I'm having issues with logging on. 
I try to create an account, however after I enter my username and password, it never lets me log on.

**Comment by pingsutw** [comment]
@vinhdiesal welcome to the Submarine
You could install submarine on K8s by `helm install submarine ./helm-charts/submarine`, refer to https://github.com/apache/submarine/blob/master/docs/userdocs/k8s/helm.md
And then log in to the workbench with default username `admin`, password `admin` 

If you faced any problem, let me know.

**Comment by vinhdiesal** [comment]
I installed helm and access the submarine login page at localhost:8080, however I username:: `admin` and password `admin` is not working.

**Comment by pingsutw** [comment]
@vinhdiesal Did you make sure all pods start properly? 
Could I see the output of `kubectl get pods`

**Comment by vinhdiesal** [comment]
Here are the results of get pod

```
default                pod/notebook-controller-deployment-55c8b5f57f-dnk8p       1/1     Running             1          41h
default                pod/pytorch-operator-565d9769cc-zlmgh                     1/1     Running             3          41h
default                pod/submarine-database-75b9d48759-sqftf                   1/1     Running             1          41h
default                pod/submarine-server-b464b7cd-xjg4v                       1/1     Running             1          41h
default                pod/tf-job-operator-787b45dc6b-cghxr                      1/1     Running             5          41h
```

**Comment by jiwq** [comment]
@vinhdiesal Could you attach to the database container and connect to the MySQL service then execute `select * from sys_user;`?
