### ISSUE TITLE
Double-Checked Locking

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [apache/submarine#381]
https://github.com/apache/submarine/blob/3060ef754d26b7d1e514cd0e2836cf55ab5e8ab2/submarine-commons/commons-utils/src/main/java/org/apache/submarine/commons/utils/SubmarineConfiguration.java#L89-L92

double-Checked Locking is widely cited and used as an efficient method for implementing lazy initialization in a multithreaded environment.
Unfortunately, it will not work reliably in a platform independent way when implemented in Java, without additional synchronization.

**Comment by jiwq** [comment]
@QiAnXinCodeSafe Thanks for your report, I had create one JIRA to track it: https://issues.apache.org/jira/browse/SUBMARINE-604 
Could you give us your apache jira account id? So that we can change the reporter to you in the Apache JIRA system.
