### ISSUE TITLE
spark-security Ranger plugin is not masking when a function is used around the column

### ISSUE THREAD

**Issue by harsha-tenneti** [apache/submarine#403]
When a column has masking policies configured and the column is called inside a function. The output of the function is not returning masked data.

For example, let's say if a column `abc` from table `default_table` has `HASH_MASK` policy configured for a user `XYZ`. Below are a couple of queries where the user might get actual `abc` value instead of masked value.

```
select substr(abc, 0, 100000000000)  from default_table
select concat(abc, '-', 'dummy') from default_table
```

**Comment by pingsutw** [comment]
cc @xunliu
