### ISSUE TITLE
[Submarine Spark Security] if  spark read/write data from/to s3, spark security support ranger-hadoop-aws plugin?

### ISSUE THREAD

**Issue by cloudkey** [apache/submarine#452]

**Comment by cloudkey** [comment]
I'm using hadoop-aws-2.8.5.jar enable spark read/write data from/to s3, but I want the spark security to support s3 request through hadoop-aws jar.

**Comment by yaooqinn** [comment]
Submarine spark security module authorizes w/ metadata. For your case w/ s3, the ACLs that reading data directly from storage should be controlled by s3.
