### ISSUE TITLE
can submarine build on arm64 machine now

### ISSUE THREAD

**Issue by zhuhb1** [apache/submarine#472]
hi, everyone
can submarine build on arm64 machine now?

**Comment by jiwq** [comment]
Thanks @zhuhb1 for following the submarine project. 🎉 Nowadays the submarine can not build on arm64, welcome to contribute this feature.

**Comment by zhuhb1** [comment]
does "supporting arm64" on submarine's roadmap ?

**Comment by jiwq** [comment]
@zhuhb1 No plans yet, because the community is concentrating on ensuring stable development.
