### ISSUE TITLE
[Submarine Spark Security] Policy Download Performance

### ISSUE THREAD

**Issue by jasonkoo** [apache/submarine#551]
In a large cluster with hundreds of Spark jobs running simultaneously and tens of thousands of ranger policies created， when restarting the cluster, these Spark jobs will try to download ranger policies at the same time and Ranger Admin will be under a huge pressure. Can Ranger Admin withstand such a huge load ? Does anyone know how to deal with this special situation?

**Comment by brucemen711** [comment]
I think we can have another solution for this, if you at that scale.

**Comment by xunliu** [comment]
The [Submarine Spark Security] functionality has been moved to the apache/incubator-kyuubi standalone project.
