### ISSUE TITLE
Spark security does not use the beeline connected user.

### ISSUE THREAD

**Issue by SananGuliyev** [apache/submarine#789]
I am using ranger 2.1 and spark 3.1.

I use (e.g. user: root) spark submit for running  HiveThriftServer2. After successful submit I use the beeline to connect to thriftserver but it does not use the user (e.g.user: test) which I connected while making connection with beeline. 

Expected result: spark security should check permissions for user `test` which I used for beeline connection
Actual: spark security is using `root` which I have executed the the spark submit for running thrift server. I can change it with --proxy-user option but it will still use the same user for all connection.

**Comment by yaooqinn** [comment]
HiveThriftServer2 does not support proxying, maybe you can try apache/incubator-kyuubi https://github.com/apache/incubator-kyuubi

**Comment by xunliu** [comment]
The [Submarine Spark Security] functionality has been moved to the apache/incubator-kyuubi standalone project.
