### ISSUE TITLE
[Submarine Spark Security] Different masking policies for different tables fail in the case of union

### ISSUE THREAD

**Issue by qiuliang988** [apache/submarine#795]
Hi, We ran into a problem with Submarine's Spark Security for Column Masking
For example, 
select col_1, col_2 from tbl_1 union select col_3, col_4 from tbl_2
If masking policies for col_2 and col_4 are different, col_4 will use col_2's policy instead of its own
because col_4 is not in "plan.output"
![image](https://user-images.githubusercontent.com/67689926/141068525-6bb2f58e-3b57-40ed-b91a-f14c618e05c3.png)

**Comment by Junyewu** [comment]
I also encountered the same problem.

**Comment by harsha-tenneti** [comment]
What is the expected output in this case?

**Comment by turtoise** [comment]
Hi,I was also using spark security plugin to authorize SparkSQL,but when i execute command "show tables " or any sql command ,it report below errors:

22/01/11 10:23:26 WARN PolicyRefresher: cache file does not exist or not readable '/etc/ranger/sparkServer/policycache/sparkSql_sparkServer.json'

I have no idea why would this happen even though i configured a sparkService in hive in ranger?
![image](https://user-images.githubusercontent.com/19393229/148870991-bf4e0ca3-9ba9-45e2-a009-d6342edaa120.png)

**Comment by xunliu** [comment]
The [Submarine Spark Security] functionality has been moved to the apache/incubator-kyuubi standalone project.
