### ISSUE TITLE
Can't build helm chart submarine from quick start guide 

### ISSUE THREAD

**Issue by Mentalsupernova** [apache/submarine#977]
W0709 19:38:47.901294   57381 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: resource mapping not found for name: "submarine-gateway" namespace: "" from "": no matches for kind "Gateway" in version "networking.istio.io/v1alpha3"
ensure CRDs are installed first

**Comment by Mentalsupernova** [comment]
Just decreased version to 0.7.0

**Comment by vojteq** [comment]
hi @Mentalsupernova could you please tell me what version you downgraded?
